### PR TITLE
Home Page

### PR DESCRIPTION
**Pull request by Abhiram716**
### Desktop version
Screenshot from 2023-07-21 19-30-27

### Mobile version

Screenshot from 2023-07-21 19-31-03

### CODE REVIEW

**Comment by Abhiram716** [comment]
@aadilmughal786 right now we don't have the option for a preview deployment link if you are willing, please clone the project and check out the project locally and suggest any changes design-wise and code-wise if you can.

**Review by aadilmughal786 — APPROVED** [review]
Looks good to me

**Comment by Abhiram716** [comment]
@aadilmughal786 I found an issue when I change to the mobile version and then to landscape mode the text content is disappearing from the viewport due to the lack of height. can you suggest something to solve this issue?

**Review by aadilmughal786 — APPROVED** [review]
Looking nice 🙂

**Pull request merged**
